mailserver:
  image: hardware/mailserver
  container_name: mailserver
  domainname: domain.tld                # Mail server FQDN & reverse = mail.domain.tld.
  hostname: mail
  links:
    - mariadb:mariadb
  # extra_hosts:                        - Required for external database (on other server or for local database on host)
  #  - "mariadb:xx.xx.xx.xx"            - Replace with IP address of MariaDB server
  ports:
    - "25:25"     # SMTP                - Required
    - "110:110"	  # POP3
    - "143:143"   # IMAP       STARTTLS - For webmails/desktop clients
    - "465:465"   # SMTPS      SSL/TLS  - Enabled for compatibility reason, otherwise disabled
    - "587:587"   # Submission STARTTLS - For webmails/desktop clients
    - "993:993"   # IMAPS      SSL/TLS  - For webmails/desktop clients
    - "995:995"   # POP3S
    - "4190:4190" # SIEVE      STARTTLS - Optional, but recommended for mail filtering
  environment:
    - DBPASS=xxxxxxx
  volumes:
    - /mnt/docker/mail:/var/mail
    - /mnt/docker/opendkim:/etc/opendkim/keys

# Control panel
postfixadmin:
  image: hardware/postfixadmin
  container_name: postfixadmin
  domainname: domain.tld
  hostname: mail
  links:
    - mailserver:mailserver
    - mariadb:mariadb
  environment:
    - DBPASS=xxxxxxx

# Webmail
rainloop:
  image: hardware/rainloop
  container_name: rainloop
  links:
    - mailserver:mailserver
    - mariadb:mariadb
  volumes:
    - /mnt/docker/rainloop:/rainloop/data

# Web server
nginx:
  image: wonderfall/nginx
  container_name: nginx
  links:
    - postfixadmin:postfixadmin
    - rainloop:rainloop
  ports:
    - "80:8000"
    - "443:4430"
  volumes:
    - /mnt/docker/nginx/sites-enabled:/sites-enabled
    - /mnt/docker/nginx/conf:/conf.d
    - /mnt/docker/nginx/log:/var/log/nginx
    - /mnt/docker/nginx/certs:/certs

# Database
mariadb:
  image: mariadb:10.1
  container_name: mariadb
  # Info : These variables are ignored when the volume already exists (databases created before).
  environment:
    - MYSQL_ROOT_PASSWORD=xxxxxxx
    - MYSQL_DATABASE=postfix
    - MYSQL_USER=postfix
    - MYSQL_PASSWORD=xxxxxxx
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
